version: '3.8'
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis_stack_carbidding
    ports:
      - "6379:6379"  # Redis
      - "8001:8001"  # RedisInsight
volumes:
  redis_data:
    driver: local